import type {
  AssistantCitation,
  AssistantConversation,
  AssistantMessage,
} from '@/modules/ai-assistant/api';

export const assistantScreenFallbacks = {
  messages: [
    {
      id: 'msg-1',
      conversationId: 'conv-1',
      role: 'ASSISTANT' as const,
      content: 'Hello! I am your ManaBandhu assistant. How can I help you today?',
      body: 'Hello! I am your ManaBandhu assistant. How can I help you today?',
      createdAt: new Date().toISOString(),
      time: '10:30 AM',
      sent: false,
    },
    {
      id: 'msg-2',
      conversationId: 'conv-1',
      role: 'USER' as const,
      content: 'I need help finding a room near DFW with vegetarian-friendly roommates.',
      body: 'I need help finding a room near DFW with vegetarian-friendly roommates.',
      createdAt: new Date().toISOString(),
      time: '10:31 AM',
      sent: true,
    },
    {
      id: 'msg-3',
      conversationId: 'conv-1',
      role: 'ASSISTANT' as const,
      content: 'I found 3 matches. Would you like me to summarize trust signals and commute times?',
      body: 'I found 3 matches. Would you like me to summarize trust signals and commute times?',
      createdAt: new Date().toISOString(),
      time: '10:31 AM',
      sent: false,
    },
  ] satisfies AssistantMessage[],
  history: [
    {
      id: 'conv-1',
      title: 'Room search near DFW',
      body: 'Discussed budget, move-in date, and household preferences.',
      meta: 'Yesterday',
      route: '/assistant',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'conv-2',
      title: 'Ride to temple',
      body: 'Found carpools for Sunday morning from Irving.',
      meta: '3 days ago',
      route: '/assistant',
      createdAt: new Date(Date.now() - 259200000).toISOString(),
      updatedAt: new Date(Date.now() - 259200000).toISOString(),
    },
  ] satisfies AssistantConversation[],
  citations: [
    {
      id: 'cite-1',
      messageId: 'msg-1',
      title: 'Community guidelines',
      url: 'app://handbook',
      snippet: 'Respectful communication, privacy boundaries, and moderation rules.',
      body: 'Respectful communication, privacy boundaries, and moderation rules.',
      meta: 'Manabandhu handbook',
      source: 'app://handbook',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'cite-2',
      messageId: 'msg-1',
      title: 'Trust and safety FAQ',
      url: 'app://help',
      snippet: 'How reporting, blocking, and trusted contacts work.',
      body: 'How reporting, blocking, and trusted contacts work.',
      meta: 'Help center',
      source: 'app://help',
      createdAt: new Date().toISOString(),
    },
  ] satisfies AssistantCitation[],
};
