import type { HomeShellData } from '@/modules/foundation/homeApi';

export const homeShellFallbacks: Record<string, HomeShellData> = {
  home: {
    eyebrow: 'ManaBandhu',
    title: 'Your community, today',
    subtitle: 'Rooms, rides, jobs, events, and community posts personalized for you.',
    greetingName: 'friend',
    metrics: [
      { label: 'New matches', value: '6' },
      { label: 'Messages', value: '3' },
      { label: 'Saved', value: '12' },
    ],
    feed: [
      {
        id: 'room-1',
        kind: 'room',
        title: 'Sunny room in Downtown',
        body: 'Furnished room with utilities included.',
        meta: '$850/mo',
        route: '/rooms',
      },
      {
        id: 'ride-1',
        kind: 'ride',
        title: 'Ride offered to SF',
        body: 'Driving from SJ to SF this Friday at 5 PM. 2 seats available.',
        meta: 'Today',
        route: '/rides',
      },
      {
        id: 'post-1',
        kind: 'post',
        title: 'Kiran asked a question',
        body: 'Does anyone know a good, affordable moving service for a 1BHK?',
        meta: 'Community',
        route: '/community',
      },
    ],
  },
  explore: {
    eyebrow: 'Explore',
    title: 'Everything nearby',
    subtitle: 'Jump into rooms, rides, jobs, events, and community posts from one surface.',
    greetingName: 'explorer',
    metrics: [
      { label: 'Modules', value: '9' },
      { label: 'Saved searches', value: '4' },
    ],
    feed: [
      {
        id: 'room-2',
        kind: 'room',
        title: 'Rooms',
        body: 'Find shared housing and trusted listings.',
        meta: 'Open now',
        route: '/rooms',
      },
      {
        id: 'ride-2',
        kind: 'ride',
        title: 'Rides',
        body: 'Offer or request safe local and airport rides.',
        meta: 'Open now',
        route: '/rides',
      },
      {
        id: 'job-1',
        kind: 'job',
        title: 'Jobs',
        body: 'Browse openings with referrals and trusted applications.',
        meta: 'Open now',
        route: '/jobs',
      },
    ],
  },
  chat: {
    eyebrow: 'Chat',
    title: 'Your conversations',
    subtitle: 'Private and group chats with community members.',
    greetingName: 'friend',
    metrics: [
      { label: 'Unread', value: '3' },
      { label: 'Groups', value: '8' },
    ],
    feed: [
      {
        id: 'conv-1',
        kind: 'post',
        title: 'Sarah Jenkins',
        body: 'Are we still on for coffee later? ☕️',
        meta: '10:42 AM',
        route: '/chat',
      },
      {
        id: 'conv-2',
        kind: 'post',
        title: 'Design Team',
        body: 'I uploaded the new assets to the drive.',
        meta: 'Yesterday',
        route: '/chat',
      },
    ],
  },
  community: {
    eyebrow: 'Community',
    title: 'Your hubs',
    subtitle: 'Join groups, follow topics, and read the activity feed.',
    greetingName: 'friend',
    metrics: [
      { label: 'Hubs', value: '4' },
      { label: 'Posts today', value: '27' },
    ],
    feed: [
      {
        id: 'hub-1',
        kind: 'post',
        title: 'Bay Area Indians',
        body: 'Planning a casual meetup this Saturday at Dolores Park!',
        meta: '2h ago',
        route: '/community',
      },
      {
        id: 'hub-2',
        kind: 'post',
        title: 'Desi Techies',
        body: 'Weekly study session for system design interview prep.',
        meta: '5h ago',
        route: '/community',
      },
    ],
  },
  profile: {
    eyebrow: 'Profile',
    title: 'Your community profile',
    subtitle: 'Manage your visible name, trust signals, interests, and contact privacy.',
    greetingName: 'user',
    metrics: [
      { label: 'Profile strength', value: '72%' },
      { label: 'Trust checks', value: '2' },
    ],
    feed: [
      {
        id: 'identity',
        kind: 'post',
        title: 'Identity and privacy',
        body: 'Control your display name, pronouns, language, and location precision.',
        meta: 'Editable',
        route: '/settings',
      },
      {
        id: 'activity',
        kind: 'post',
        title: 'Recent activity',
        body: 'Your posts, listings, rides, saves, and community contributions.',
        meta: 'Private by default',
        route: '/saved',
      },
    ],
  },
};
